### PR TITLE
Link duplicated fix

### LINKED ISSUE #43: Link being duplicated multiple times when adding a new link in the nav.
Some weird behavior happening when editing the nav. If you add a new link and then edit the target of that link, sometimes it will create a duplicate link in the left nav instead of just changing the target. 

**Steps to reproduce:**
1. Go to https://tina-starter-alpaca.now.sh
2. Enter edit mode
3. Click the hamburger menu in the top left
4. Click Navigation
5. Click the + button to add a new page to the doc list
6. Click to edit the newly added page
7. Start switching the option in the "Choose linked page" select field.
8. You'll see that a new page is being added to the nav multiple times behind the modal.

**Expected Result**
Only one link should be created in that left nav, and changing the linked page should change the destination of the link, not add a new one.

Here's a video

https://www.loom.com/share/2f0cdd1edca84fdb8225abb002c1f229

### PR DESCRIPTION
**Pull request by logan-anderson**
This should fix #43 
**NOTE:** this will break any previous branches that will made of master as they will not have an ```id```

### CODE REVIEW

File: hooks/useNavigationForm.js [hunk 1]
```diff
@@ -45,13 +45,15 @@ const useNavigationForm = (jsonFile, preview) => {
...
       itemProps: (item) => ({
+        key: item.id,
         label: `${item.title} (${item.type})`,
       }),
       defaultItem: () => ({
         type: "link",
         slug: "getting-started",
         title: "new doc page",
         children: [],
+        id: Math.random().toString(36).substr(2, 9),
```
Comment (mittonface) [inline hooks/useNavigationForm.js:56]: Might as well toss this into a utility function, just in case we ever want to use it anywhere else or ever want to switch this to use UUIDs or something.

Other than that, this fixed the issue!

Comment (logan-anderson) [reply hooks/useNavigationForm.js]: @mittonface Good catch I also forgot to add the ID to the content-creator plugin. fixed that as well
